### ISSUE TITLE
Thoughts on -square versions of icons (vs not square)

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/on_the_web#20]
Initially I thought we should use the -square versions of all these font-awesome brand icons since those were more similar to the previous icons, but as people are asking for new services to be added, it looks like the -square version of the icons come later than the non-square version, meaning there may be a delay as we wait for FontAwesome to add the new icon.

Would it be better to switch to the non-square versions?  @BWPanda these are the icons you'd selected, I was wondering if you could weigh in here on why you made that choice. Is it because of the above, or did you just prefer those?

I'll wait for feedback here before creating a new 2.x of this module.

**Comment by ghost** [comment]
I think I chose the non-square versions (e.g. http://fontawesome.io/icon/facebook/ as opposed to http://fontawesome.io/icon/facebook-square/ or http://fontawesome.io/icon/facebook-official/) simply because of the namespace: 'facebook' seems more generic and more likely to match other services (e.g. http://fontawesome.io/icon/twitter/) than -square or -official versions...

Having said that, I don't really have any inclination towards one or the other. Though I can foresee clients asking to change the icons to the opposite of whatever you decide ;-)

I'd therefore suggest having an option to choose between -square and non-square versions in the settings. From my limited searching, it seems that most social media FA icons have a regular (non-square) and a -square version, so a setting that lets you choose between them should be a fairly safe option.
Or just choose one and leave it up to developers to alter them (via HOOK_on_the_web_get_services_alter()) themselves...

Hope that helps.

**Comment by jenlampton** [comment]
Thanks for the speedy reply @BWPanda :)

> it seems that most social media FA icons have a regular (non-square) and a -square version

Yes, most of the older ones do, but if we supported 2 versions we'd need to wait for them both to exist before we could add a new service. For example, [Bandcamp](https://github.com/backdrop-contrib/on_the_web/issues/14) only has the one without the square.  That wouldn't help us add services any more quickly than using the square-only versions (since non-square seems to come first).

It's a interesting idea though... Creating another issue for that: https://github.com/backdrop-contrib/on_the_web/issues/21
